[package]
name = "graphitude"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative = "2.2"
pathfinding = { version = "4.14.0", optional = true }
bitvec = { version = "1.0.1", optional = true }
dot = { version = "0.1", optional = true }

[features]
default = [
  "pathfinding",
  "bitvec",
]
dot = [
  "dep:dot",
]
pathfinding = [
  "dep:pathfinding",
]
bitvec = [
  "dep:bitvec",
]
unchecked = [
]
