[package]
name = "jrw-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
pathfinding = { version = "4.14.0", optional = true }
bitvec = { version = "1.0.1", optional = true }

[features]
default = [
  "pathfinding",
  "bitvec",
  "paranoia",
]
pathfinding = [
  "dep:pathfinding",
]
bitvec = [
  "dep:bitvec",
]
paranoia = [
]
