[package]
name = "jrw-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
pathfinding = { version = "4.14.0", optional = true }
bitvec = { version = "1.0.1", optional = true }
double_vec_queue = {path = "../double_vec_queue"}
maybe_mut = {path = "../maybe_mut"}

[features]
nope = []
default = [
  "pathfinding", "bitvec",
]
pathfinding = [
  "dep:pathfinding",
]
bitvec = [
  "dep:bitvec",
]
